-- 0003_sessions: the C4 session registry (§6). This epic lands the
-- trust plumbing — trust_floor and the schema-enforced invariants; the
-- router that creates and rotates rows is M1 work. The tainted column
-- arrives in a later migration with its set-on-ingest plumbing (§7).
CREATE TABLE sessions (
    thread_key   TEXT NOT NULL,        -- per-channel contract (§6), incl. task:<issue-id> workers
    session_id   TEXT NOT NULL,        -- UUID generated BY THE DAEMON, spawned via --session-id —
                                       --   never captured from engine output (§4.1)
    status       TEXT NOT NULL DEFAULT 'creating'
        CHECK (status IN ('creating', 'active', 'rotated', 'resume_failed', 'failed')),
                                       -- creating → active → rotated (on /new, idle TTL, turn cap)
                                       --   | resume_failed (transcript lost — rotation cause, §4.6)
                                       --   | failed (creating past deadline — retried fresh, §4.1)
    cwd          TEXT NOT NULL,        -- spawn/resume dir (--resume is scoped to it — assert at spawn)
    origin       TEXT,                 -- task:* workers: thread that spawned the work (§4.5)
    trust_floor  TEXT NOT NULL         -- MIN trust of any participant this thread can admit
        CHECK (trust_floor IN ('owner', 'known', 'untrusted')),
                                       --   (§4.3, §7): DM = that identity; group = whoever can post
                                       --   there. Retrieval + the policy matrix key off THIS, not
                                       --   the current sender — owner-private facts never assemble
                                       --   into a multi-party session. Participant levels only:
                                       --   system trust is daemon-stamped on events, never a floor.
    created_at   INTEGER NOT NULL,
    activation_deadline INTEGER,       -- 'creating' past this ⇒ 'failed', retried fresh (§4.1)
    rotated_to   TEXT REFERENCES sessions(session_id),
                                       -- successor link on rotation. The spec sketch says
                                       --   REFERENCES sessions(rowid), but SQLite cannot enforce a
                                       --   foreign key onto the implicit rowid (parent keys must be
                                       --   declared, uniquely-indexed columns) — with foreign_keys=ON
                                       --   every insert would fail "foreign key mismatch". session_id
                                       --   is globally unique below, so the successor link binds to it.
    channel      TEXT,
    last_seen    INTEGER,
    turns        INTEGER,
    PRIMARY KEY (thread_key, session_id)
);

-- session_id is addressed alone by session_facts/approvals/log_entries,
-- so it must be globally unique.
CREATE UNIQUE INDEX sessions_by_id ON sessions(session_id);

-- THE router invariant, enforced in schema: at most one live session per
-- thread. Rotation = one transaction (old→rotated + new→creating); any
-- bad interleaving is a constraint violation, not a race.
CREATE UNIQUE INDEX one_live_session ON sessions(thread_key)
    WHERE status IN ('creating', 'active');

-- Worker exclusivity: at most one live worker per repo path (§4.5, §7 X8).
CREATE UNIQUE INDEX one_worker_per_repo ON sessions(cwd)
    WHERE status IN ('creating', 'active') AND thread_key LIKE 'task:%';
