package store

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Session is one row bound for the §6 session registry: the fields the
// router stamps when it pins a new session. Later lifecycle state
// (status, rotated_to, last_seen, turns) is deliberately absent — every
// session is born 'creating' (§4.1) and only the router flows that own
// those transitions may set them. The activation deadline IS here: a
// creating row is live under one_live_session, so it must carry its
// recovery deadline from birth — written in the same INSERT, never a
// follow-up update a crash could separate from it.
type Session struct {
	ThreadKey          string // per-channel contract (§6), incl. task:<issue-id> workers
	SessionID          string // UUID generated BY THE DAEMON (§4.1) — never engine output
	Cwd                string // spawn/resume dir; canonicalized before insert (see below)
	Origin             string // task:* workers: thread that spawned the work (§4.5); "" → NULL
	TrustFloor         string // MIN trust any participant this thread can admit (§4.3, §7)
	CreatedAt          int64  // unix seconds
	ActivationDeadline int64  // unix seconds; 'creating' past this ⇒ 'failed', retried fresh (§4.1)
}

// InsertSession is the single chokepoint for creating session rows.
// The cwd is canonicalized (absolute, symlinks resolved, cleaned)
// BEFORE insert — one_worker_per_repo compares cwd TEXT, and SQLite
// cannot canonicalize in-schema, so this is where the §4.5/§7 X8
// worker-exclusivity invariant is made spelling-proof: /repo, a symlink
// alias, and a dot-dot spelling of the same checkout all collapse to
// one canonical path and collide in the index. A cwd that does not
// resolve is an ERROR, not a row: the daemon spawns the engine from
// sessions.cwd (§4.1, §6), and a session pointing nowhere would fail
// later and quieter. Constraint violations (one_live_session,
// one_worker_per_repo, sessions_by_id) surface loud — transactional
// rotation belongs to the rotation flow, not here.
func InsertSession(ctx context.Context, db *sql.DB, s Session) error {
	if err := s.validate(); err != nil {
		return fmt.Errorf("store: insert session: %w", err)
	}
	cwd, err := canonicalCwd(s.Cwd)
	if err != nil {
		return fmt.Errorf("store: insert session %s: %w", s.SessionID, err)
	}
	if _, err := db.ExecContext(ctx,
		`INSERT INTO sessions (thread_key, session_id, cwd, origin, trust_floor, created_at, activation_deadline)
		 VALUES (?, ?, ?, NULLIF(?, ''), ?, ?, ?)`,
		s.ThreadKey, s.SessionID, cwd, s.Origin, s.TrustFloor, s.CreatedAt, s.ActivationDeadline,
	); err != nil {
		return fmt.Errorf("store: insert session %s: %w", s.SessionID, err)
	}
	return nil
}

// canonicalCwd resolves one true spelling for a session's working
// directory: absolute, every symlink resolved, lexically clean.
// EvalSymlinks also stats the path, so a missing directory fails here
// — fail closed, never store a dir the daemon cannot spawn from.
// Deliberately NOT derived here: a repository identity. Spelling
// aliases of one directory collapse; /repo vs /repo/subdir do not —
// worker cwd is the repo ROOT by the router's spawn contract (§4.5),
// and that contract's enforcement belongs to the router (approach-ov7).
// Likewise case/Unicode aliases on case-insensitive filesystems stay
// distinct: folding case HERE would falsely collide distinct repos on
// the case-sensitive Linux deployment target (§8). A filesystem-stable
// repository key is approach-ov7's remit, alongside the repo-root rule.
func canonicalCwd(cwd string) (string, error) {
	abs, err := filepath.Abs(cwd)
	if err != nil {
		return "", fmt.Errorf("canonicalize cwd %q: %w", cwd, err)
	}
	resolved, err := filepath.EvalSymlinks(abs)
	if err != nil {
		return "", fmt.Errorf("canonicalize cwd %q: %w", cwd, err)
	}
	// EvalSymlinks proves the path exists, not that it's a directory —
	// a regular file would sit in the exclusivity indexes as a live row
	// the engine can never spawn from, wedging the thread.
	info, err := os.Stat(resolved)
	if err != nil {
		return "", fmt.Errorf("canonicalize cwd %q: %w", cwd, err)
	}
	if !info.IsDir() {
		return "", fmt.Errorf("cwd %q is not a directory", cwd)
	}
	return resolved, nil
}

// isWorkerThreadKey mirrors the one_worker_per_repo index predicate
// (thread_key LIKE 'task:%') — one definition of "worker", not two.
func isWorkerThreadKey(threadKey string) bool {
	return strings.HasPrefix(threadKey, "task:")
}

// validate refuses a session the daemon could not honestly resume or
// spawn. Enum membership (trust_floor) is the schema CHECK's job.
func (s Session) validate() error {
	switch {
	case s.ThreadKey == "":
		return fmt.Errorf("empty thread_key")
	case s.SessionID == "":
		return fmt.Errorf("empty session_id — the daemon pins the UUID before insert (§4.1)")
	case s.Cwd == "":
		return fmt.Errorf("empty cwd — every session records its spawn dir (§6)")
	case s.TrustFloor == "":
		return fmt.Errorf("empty trust_floor — ambiguity is a floor of untrusted, not blank (§4.3)")
	case s.CreatedAt <= 0:
		return fmt.Errorf("created_at = %d, want a positive unix timestamp", s.CreatedAt)
	case s.ActivationDeadline <= 0:
		return fmt.Errorf("activation_deadline = %d, want a positive unix timestamp — a creating row without one can wedge one_live_session forever (§4.1)", s.ActivationDeadline)
	case s.ActivationDeadline <= s.CreatedAt:
		// Born expired: the recovery sweep would mark it failed while
		// the engine is still being spawned — a retry loop, not a row.
		return fmt.Errorf("activation_deadline %d is not after created_at %d", s.ActivationDeadline, s.CreatedAt)
	case isWorkerThreadKey(s.ThreadKey) && s.Origin == "":
		// Workers report transcript loss, reconciliation, and progress
		// back to the thread that spawned them (§4.5) — a worker row
		// without an origin is durably mute after a restart.
		return fmt.Errorf("task session %s has no origin thread (§4.5)", s.ThreadKey)
	}
	return nil
}
